In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

#IRIS 데이터 로드
iris =  sns.load_dataset('iris') 
X= iris.iloc[:,:4] #학습할데이터
y = iris.iloc[:,-1] #타겟

In [11]:
#Scailing
scal = StandardScaler() 
X = scal.fit_transform(X) #X를 스케일링한 데이터로 교체

In [6]:
# One Versus Rest 구현을 위해 class가 0인것과 아닌것을 구분하기위한 machine class가 1인것과 아닌 것을 구분하기 위한 머신 등을 미리만들어줌
svm_1 = SVC(kernel ='rbf', C = 5, gamma = 5)
svm_2 = SVC(kernel ='rbf', C = 5, gamma = 5)
svm_3 = SVC(kernel ='rbf', C = 5, gamma = 5)

In [7]:
from sklearn.model_selection import train_test_split #테스트/트레인 데이터로 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=48)

In [8]:
y_train = pd.get_dummies(y_train) #one hot encoding을 먼저해보자
y_train

setosa  versicolor  virginica
110       0           0          1
69        0           1          0
148       0           0          1
39        1           0          0
53        0           1          0
..      ...         ...        ...
64        0           1          0
91        0           1          0
81        0           1          0
51        0           1          0
0         1           0          0

[120 rows x 3 columns]

In [23]:
svm_1.fit(X_train,y_train.iloc[:,0]) # 데이터 클레스가 0인 애인지 아닌지 구분해주는 머신
svm_2.fit(X_train,y_train.iloc[:,1]) # 데이터 클레스가 1인 애인지 아닌지 구분해주는 머신
svm_3.fit(X_train,y_train.iloc[:,2]) # 데이터 클레스가 2인 애인지 아닌지 구분해주는 머신

SVC(C=5, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=5, kernel='rbf', max_iter=-1,
    probability=False, random_state=None, shrinking=True, tol=0.001,
    verbose=False)

In [24]:
print(svm_1.predict(X_test)) #데이터 클래스가 0인지 아닌지 구분해주는 애를 통해서 테스트데이터의 클래스가 0인지 0이 아닌인지 예측해보자
print(svm_1.decision_function(X_test)) #decision_function hyperplane과의 거리를 구하는 방법 필요하다면 활용해주세요

[0 0 0 0 0 0 1 0 1 0 0 1 1 0 0 0 1 0 0 0 1 0 0 0 0 1 1 0 0 0]
[-1.12470845 -0.86326953 -0.65281099 -0.50248821 -0.76284323 -0.87465573
  1.07709345 -0.99281647  0.47441336 -0.99842743 -0.83989348  0.15633457
  0.32871788 -0.97965464 -0.72385083 -0.92638376  1.28322481 -0.56240455
 -0.72719892 -0.99509775  0.43166724 -0.96451557 -0.82991366 -1.03020581
 -0.75166835  1.13461335  0.39943974 -1.04194106 -0.93376548 -1.06133798]


In [25]:
print(svm_2.predict(X_test)) #데이터 클래스가 0인지 아닌지 구분해주는 애를 통해서 테스트데이터의 클래스가 0인지 0이 아닌인지 예측해보자
print(svm_2.decision_function(X_test)) #decision_function hyperplane과의 거리를 구하는 방법 필요하다면 활용해주세요

[1 1 1 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 1 1 0 0 0 0 0 1]
[ 1.36054602  0.62859488  0.0580828  -0.36987093 -0.25686625 -0.79229874
 -1.03195247 -0.87132049 -0.77957234  0.99327762 -0.73309581 -0.64607768
 -0.71843897 -0.80882458  0.47748663  0.69953462 -1.11879121 -0.1870504
 -0.24458236 -0.99337352 -0.76149141 -0.96812018  0.11310267  1.06892719
 -0.56749692 -1.05639624 -0.74817515 -1.0537858  -0.89721836  1.17126024]


In [26]:
print(svm_3.predict(X_test)) #데이터 클래스가 0인지 아닌지 구분해주는 애를 통해서 테스트데이터의 클래스가 0인지 0이 아닌인지 예측해보자
print(svm_3.decision_function(X_test)) #decision_function hyperplane과의 거리를 구하는 방법 필요하다면 활용해주세요

[0 0 0 0 1 1 0 1 0 0 1 0 0 1 0 0 0 0 0 1 0 1 0 0 1 0 0 1 1 0]
[-1.26277651 -0.77964936 -0.40539105 -0.13070947  0.02643314  0.57365649
 -1.04443118  0.88027844 -0.69605517 -0.99074328  0.52442024 -0.51171892
 -0.61157919  0.78148257 -0.75517707 -0.76905925 -1.16380018 -0.25333938
 -0.0251979   0.98843144 -0.67129528  0.89577306 -0.30363489 -1.03647008
  0.31622662 -1.07758405 -0.65251719  1.09632055  0.85541707 -1.11042784]


In [33]:
# 부호가 모든 같은 경우가 있는가? 요모두 동점인 경우가 생길것이다.
for i in range(len(X_test)):
    # ~. decision_function을 이용하면 해당 데이터가 하이퍼플레인으로부터 얼마나 떨어져있는 지 거리가 나온다 다음은 그 값의 부호를 이용해
    # 모두가 동점인 경우가 있는지 출력하는 함수 
    if (np.sign(svm_1.decision_function(X_test)[i]) == np.sign(svm_2.decision_function(X_test)[i])) and (np.sign(svm_2.decision_function(X_test)[i]) == np.sign(svm_3.decision_function(X_test)[i])):
        print(i)

3
17
18


# SVM :: One vs rest
 Case 1 : One vs Rest SVM을 이부분에 구현해주세요 위 결과들을 이용해서 multi class SVM을 직접 구현해주세요! 하드코딩이 하시기 편할겁니다.


In [226]:
#각 모델의 결과를 ndarray에 넣고 합침. 
# svm_t는 2차원 배열의 형태로 1열은 A모델의 결과, 2열은 B모델의 결과, 3열은 C모델의 결과를 담고 있다.
svm1 = svm_1.predict(X_test)
svm2 = svm_2.predict(X_test)
svm3 = svm_3.predict(X_test)
svm_t = np.column_stack([svm1.T, svm2.T, svm3.T])

In [227]:
#초기 인자 선언
# svm_res : 각 레코드에 대해 세 가지 모델이 투표한 결과를 담은 array, 0~3의 값을 가진다.
svm_res = []

for i in range(len(svm_t)): #for문으로 각 레코드를 차례대로 순환한다.
    sum = 0 #레코드의 시작마다 sum을 초기화시킴.
    
    for j in range(3): #각 svm1, svm2, svm3 모델에 대해 순환한다.
        sum += svm_t[i][j] #하나의 레코드에 대해 각 머신의 결과 (0 or 1)를 더함.
    
    svm_res.append(sum) #한 레코드에 대해 순환이 되었으면 해당 결과를 sum_res에 넣고 다음 레코드로 이동

In [228]:
#그리고 위에서 얻은 결과를 기존 세 가지 모델의 결과가 들어있던 데이터와 합침.
# svm_tres : 각 머신에 대한 결과와 투표수의 합이 들어있는 2차원 배열
svm_tres = np.column_stack([svm_t, svm_res])

In [229]:
#레코드가 받은 총 투표수를 이용해 결과를 return하는 함수
def vote(svm_tres):
    vote_res = []
    for i in range(len(svm_tres)):
        if svm_tres[i][3] == 1: #투표를 하나 받은 경우
            vote_res.append(single_vote(i))
    
        elif svm_tres[i][3] == 0: #투표를 아무것도 받지 못한 경우
            vote_res.append(zero_vote(i))
        
        else: #투표를 두 개 이상 받은 경우
            vote_res.append(multi_vote(i))
    return vote_res

In [230]:
#레코드가 투표를 하나 받은 경우 어떤 머신에서 투표를 받았는 지 검색하여 해당 값을 반환해주는 함수
def single_vote(i): #몇 번째 레코드인지에 대한 정보를 인자로 전달받음.
    for j in range(3):
        if svm_tres[i][j] == 1:
            return j  

In [231]:
from random import randint
#어떤 머신에서도 1값을 받지 못한 레코드의 경우 전체 경우의 수 중 랜덤으로 하나를 반환함. 그 함수임

def zero_vote(i):
    j = randint(0, 2) #0 or 1 or 2 중 하나를 랜덤으로 추출하여 해당 값을 반환함.
    return j

In [232]:
# 두 개 이상의 투표를 받은 경우에는 그 값들 중 랜덤으로 선택하여 반환함.
def multi_vote(i):
    while True:
        vote_res = randint(0, 2) #0~2사이의 난수를 추출하여
        if svm_tres[i][vote_res] == 1: #그 난수번째 머신에게 투표를 받았다면
            return vote_res #그 난수를 반환하고
            break #무한루프를 나감.
        else: #만약 난수번째 머신이 투표를 0으로 했다면
            continue #난수 추출 다시함.

In [248]:
def iris_encoding(n): #0, 1, 2로 코딩되어 있는 결과를 문자로 인코딩
    n_res = np.array([])
    for i in range(len(n)):
        if n[i] == 0:
            n_res = np.append(n_res, "setosa")
        elif n[i] == 1:
            n_res = np.append(n_res, "versicolor")
        else:
            n_res = np.append(n_res, "virginica")
    return n_res

In [306]:
svm_en = iris_encoding(vote(svm_tres))
print(svm_en)

from sklearn import metrics #model evaluation하는 라이브러리
print(metrics.accuracy_score(y_test,svm_en)) #스코어 확인

['versicolor' 'versicolor' 'versicolor' 'setosa' 'virginica' 'virginica'
 'setosa' 'virginica' 'setosa' 'versicolor' 'virginica' 'setosa' 'setosa'
 'virginica' 'versicolor' 'versicolor' 'setosa' 'versicolor' 'versicolor'
 'virginica' 'setosa' 'virginica' 'versicolor' 'versicolor' 'virginica'
 'setosa' 'setosa' 'virginica' 'virginica' 'versicolor']
0.9333333333333333


# 성능 시험
그냥 원래 라이브러리가 제공하는 멀티클래스 SVM과 여러분이 구현한 multiclass SVM결과를 한 번 비교해주세요


In [309]:
from sklearn.model_selection import train_test_split #데이터셋 분리
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(X, y, test_size=0.2, random_state=48)

svm_4 = SVC(kernel ='rbf', C = 5, gamma = 5)
svm_4.fit(X_train_2, y_train_2)
y_pred = svm_4.predict(X_test_2)

metrics.accuracy_score(y_test_2,y_pred)

0.8333333333333334

In [310]:
y_train_2 = pd.get_dummies(y_train_2) #one hot encoding을 먼저해보자
y_train_2

setosa  versicolor  virginica
110       0           0          1
69        0           1          0
148       0           0          1
39        1           0          0
53        0           1          0
..      ...         ...        ...
64        0           1          0
91        0           1          0
81        0           1          0
51        0           1          0
0         1           0          0

[120 rows x 3 columns]

In [312]:
svm_1.fit(X_train_2,y_train_2.iloc[:,0]) # 데이터 클레스가 0인 애인지 아닌지 구분해주는 머신
svm_2.fit(X_train_2,y_train_2.iloc[:,1]) # 데이터 클레스가 1인 애인지 아닌지 구분해주는 머신
svm_3.fit(X_train_2,y_train_2.iloc[:,2]) # 데이터 클레스가 2인 애인지 아닌지 구분해주는 머신|

SVC(C=5, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=5, kernel='rbf', max_iter=-1,
    probability=False, random_state=None, shrinking=True, tol=0.001,
    verbose=False)

In [313]:
svm1 = svm_1.predict(X_test_2)
svm2 = svm_2.predict(X_test_2)
svm3 = svm_3.predict(X_test_2)
svm_t = np.column_stack([svm1.T, svm2.T, svm3.T])

In [315]:
svm_res = []
for i in range(len(svm_t)): #for문으로 각 레코드를 차례대로 순환한다.
    sum = 0 #레코드의 시작마다 sum을 초기화시킴.
    for j in range(3): #각 svm1, svm2, svm3 모델에 대해 순환한다.
        sum += svm_t[i][j] #하나의 레코드에 대해 각 머신의 결과 (0 or 1)를 더함.
    svm_res.append(sum) #한 레코드에 대해 순환이 되었으면 해당 결과를 sum_res에 넣고 다음 레코드로 이동
    
svm_tres = np.column_stack([svm_t, svm_res])

In [331]:
svm_en = iris_encoding(vote(svm_tres))
print(svm_en)
print(metrics.accuracy_score(y_test_2,svm_en)) #스코어 확인

['versicolor' 'versicolor' 'versicolor' 'setosa' 'virginica' 'virginica'
 'setosa' 'virginica' 'setosa' 'versicolor' 'virginica' 'setosa' 'setosa'
 'virginica' 'versicolor' 'versicolor' 'setosa' 'setosa' 'versicolor'
 'virginica' 'setosa' 'virginica' 'versicolor' 'versicolor' 'virginica'
 'setosa' 'setosa' 'virginica' 'virginica' 'versicolor']
0.9
